[package]
name = "gatest"
version = "0.1.0"
authors = ["diddobaggins <joying0614@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
libflate_lz77 = "1.0.0"
statrs = "0.13.0"
